version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://iconstore:password@postgres:5432/iconstore
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=iconstore
      - POSTGRES_USER=iconstore
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U iconstore -d iconstore']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
